import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const siteRoot = path.resolve(scriptDirectory, "..");
const sourceRoot = path.resolve(siteRoot, "..", "docs", "beginner");
const outputPath = path.join(siteRoot, "content", "courses.generated.ts");

const documents = [
  {
    id: "course-1",
    kind: "course",
    order: 1,
    shortTitle: "环境与原理",
    title: "第 1 课：环境、项目与 Git 基本原理",
    description: "认识终端、运行 TeamFlow，并建立 Git 四区域模型。",
    duration: "60 分钟",
    file: "01-FOUNDATIONS.md",
  },
  {
    id: "course-2",
    kind: "course",
    order: 2,
    shortTitle: "提交与分支",
    title: "第 2 课：第一次提交与分支开发",
    description: "让一次修改安全经过 diff、add、commit 和分支隔离。",
    duration: "70 分钟",
    file: "02-COMMIT-AND-BRANCH.md",
  },
  {
    id: "course-3",
    kind: "course",
    order: 3,
    shortTitle: "真实功能",
    title: "第 3 课：像企业开发者一样完成真实功能",
    description: "为 TeamFlow 实现 owner 过滤，增加测试并规范提交。",
    duration: "90 分钟",
    file: "03-REAL-FEATURE.md",
  },
  {
    id: "course-4",
    kind: "course",
    order: 4,
    shortTitle: "团队协作",
    title: "第 4 课：Push、PR、Review、CI 与冲突",
    description: "把本地功能送进 GitHub，完成评审、合并和冲突实验。",
    duration: "90 分钟",
    file: "04-TEAM-COLLABORATION.md",
  },
  {
    id: "course-5",
    kind: "course",
    order: 5,
    shortTitle: "救援与发布",
    title: "第 5 课：撤销救援、进阶工具与版本发布",
    description: "学会恢复错误、处理紧急修复并完成独立毕业任务。",
    duration: "100 分钟",
    file: "05-RECOVERY-AND-RELEASE.md",
  },
  {
    id: "commands",
    kind: "reference",
    order: 6,
    shortTitle: "命令词典",
    title: "Git 命令中文词典",
    description: "按使用场景查询 Git 命令、参数、风险和示例。",
    duration: "随用随查",
    file: "COMMAND-DICTIONARY.md",
  },
  {
    id: "troubleshooting",
    kind: "reference",
    order: 7,
    shortTitle: "报错急救",
    title: "Git 常见报错急救手册",
    description: "从错误信息反推原因，优先使用不破坏历史的处理方式。",
    duration: "遇错查询",
    file: "TROUBLESHOOTING.md",
  },
];

const loadedDocuments = await Promise.all(
  documents.map(async (document) => {
    const sourcePath = path.join(sourceRoot, document.file);
    const markdown = await readFile(sourcePath, "utf8");
    const content = markdown.replace(/^#\s+[^\r\n]+\r?\n+/, "").trim();
    return {
      ...document,
      sourcePath: `docs/beginner/${document.file}`,
      content,
    };
  }),
);

const generated = `// This file is generated by scripts/sync-content.mjs.\n` +
  `// Edit the Markdown files in docs/beginner, then run npm run sync-content.\n\n` +
  `export type CourseDocument = {\n` +
  `  id: string;\n` +
  `  kind: "course" | "reference";\n` +
  `  order: number;\n` +
  `  shortTitle: string;\n` +
  `  title: string;\n` +
  `  description: string;\n` +
  `  duration: string;\n` +
  `  file: string;\n` +
  `  sourcePath: string;\n` +
  `  content: string;\n` +
  `};\n\n` +
  `export const courseDocuments: CourseDocument[] = ${JSON.stringify(loadedDocuments, null, 2)};\n`;

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, generated, "utf8");

console.log(`Synced ${loadedDocuments.length} documents to ${outputPath}`);
